---
name: Check file name case

on:
  pull_request:
    branches: [ main ]
    paths: ['docs/**']

permissions: {} # lock everything by default (least-privilege)

jobs:
  case:
    name: Check for case being inconsistent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["docs"]
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Case check action
        uses: Consensys-Incorporated/github-actions/docs-case-check@28327992dc4f4eeeee937abbaebf63f00f4f6068 # main
        with:
          DOC_DIR: ${{ matrix.folder }}
